### ISSUE TITLE
Teilnehmer in DB Einpflegen

### ISSUE THREAD

**Issue by DiFried** [Mosherfist/Boule-Petanque#2]
**Teilnehmer aufnehmen und in DB einpflegen**
> „Team_ID_“ ist Primar-Key und wird automatisch von 1 beginnend um 1 hochgesetzt.
> „_Teamname_“ wird aus Benutzereingabe gespeichert (max. 20 Zeichen)
> „_Aktiv_“ und „_Freilos_“ werden auf 0 gesetzt

**Comment by Mosherfist** [comment]
Ich habe mir das Issue(Ticket) genommen, um es zu lösen, wie lange ich benötige kann ich noch nicht sagen.

**Comment by Mosherfist** [comment]
@juliusheimann Damit die "Team_ID " automatisch um eins erhöht wird, müsste in das SQL Statement "Create Table" bei "Team_ID" die Anweisung "AUTO_INCREMENT" aufgenommen werden, ich kann das erledigen, wenn du damit einverstanden bist.
Ebenso die Limitierung der Zeichenanzahl für die unterschiedlichen Felder.

**Comment by DiFried** [comment]
Achtung die Limitierung Zeichenzahl funktioniert bei SQLITE nicht. Ich habe es gelöst und zeige es am Sonntag...

Mit freundlichen Grüßen
Dieter Friedrich

**Comment by juliusheimann** [comment]
@Mosherfist Du kannst gerne rumexperimentieren. Ich habe allerdings gelesen, dass die Auto-Increment Funktion besser nicht genutzt werden sollte. Außerdem hatten wir ja gesagt, dass an der ID auch die Runde zu erkennen sein soll. Das heißt, dass wir 3 stetige Zahlen nehmen wollen und die erste Ziffer zeigt die Runde an. Von daher würde ich die ID durch eine Python-Funktion vergeben wollen - es sei denn, du hast eine andere Idee...
